# -*- coding: utf-8 -*-
"""sme_cicids_simulated.csv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OiPio1TsIdQfOy5PhykMcsI9FMQ26QT7
"""

import numpy as np
import pandas as pd

np.random.seed(42)

n_samples = 8000  # Reduced size for stability

labels = np.random.choice(
    ['BENIGN', 'DDoS', 'PortScan', 'BruteForce', 'WebAttack'],
    size=n_samples,
    p=[0.65, 0.15, 0.1, 0.05, 0.05]
)

def gen(mean, std, size):
    return np.abs(np.random.normal(mean, std, size))

df = pd.DataFrame({
    'Flow Duration': gen(1e6, 3e5, n_samples),
    'Total Fwd Packets': gen(40, 15, n_samples),
    'Total Bwd Packets': gen(35, 12, n_samples),
    'Total Length of Fwd Packets': gen(25000, 8000, n_samples),
    'Total Length of Bwd Packets': gen(22000, 7000, n_samples),
    'Flow Bytes/s': gen(1500, 500, n_samples),
    'Flow Packets/s': gen(60, 20, n_samples),
    'Fwd IAT Mean': gen(20000, 8000, n_samples),
    'Bwd IAT Mean': gen(22000, 9000, n_samples),
    'Packet Length Mean': gen(700, 200, n_samples),
    'SYN Flag Count': np.random.poisson(2, n_samples),
    'ACK Flag Count': np.random.poisson(5, n_samples),
    'Label': labels
})

# Inject attack behaviour
df.loc[df['Label'] == 'DDoS', 'Flow Packets/s'] *= 3
df.loc[df['Label'] == 'PortScan', 'Total Fwd Packets'] *= 2
df.loc[df['Label'] == 'BruteForce', 'SYN Flag Count'] *= 4
df.loc[df['Label'] == 'WebAttack', 'Packet Length Mean'] *= 1.8

df.head()

df.to_csv('sme_cicids_simulated.csv', index=False)
print("Dataset saved successfully")

